import {CandlestickPeriod} from '@vertex-protocol/indexer-client';
export const PATHS = {
  ABOUTUS: '/about-us',
  TERMSOFUSE: '/terms-of-use',
  PRIVACY: '/privacy-policy',
  DYDX: '/dydx',
  VRTX: '/vertex',
  ANALYTICS: '/dydx/v3/volume',
  HOME: '/',
};

export const METAINFO = {
  HOME: {
    title: 'Cipher Labs',
    description: 'Crafting tools & analytics, providing elite solutions for DeFi trading.',
    twitter: '/assets/opengraph-image.png',
  },
  DYDX: {
    title: 'Cipher Labs | dYdX',
    description: "Explore Cipher Labs' dedicated suite for dYdX. From an intuitive Trading Journal to powerful Analytics Tools, we provide the edge every DeFi trader seeks.",
    twitter: '/assets/opengraph-image.png',
  },
  VRTX: {
    title: 'Cipher Labs | VRTX',
    description: "Explore Cipher Labs' dedicated suite for VRTX. From an intuitive Trading Journal to powerful Analytics Tools, we provide the edge every DeFi trader seeks.",
    twitter: '/assets/opengraph-image.png',
  },
  ABOUTUS: {
    title: 'Cipher Labs | About Us',
    description: 'Discover Cipher Labs: Dedicated craftsmen revolutionizing the DeFi landscape. Harnessing Web3, our mission is to empower traders with state-of-the-art tools and bespoke software.',
    twitter: '/assets/opengraph-image.png',
  },
  ANALYTICS: {
    title: 'dYdX v3 | Volume Analytics Dashboard',
    description: 'Experience unparalleled insights with the dYdX v3 Volume Analytics Dashboard. Dive deep into trading volume metrics, tailor-made for astute DeFi traders.',
    twitter: '/assets/twitter-analytics.jpg',
  },
};

export const COIN_COLORS = {
  BTC: ['#FEC84B'],
  ETH: ['#B692F6'],
  DOGE: ['#FEB273'],
  BCH: ['#6CE9A6'],
  SOL: ['#A6F4C5'],
  AAVE: ['#84CAFF'],
  LTC: ['#D0D5DD'],
  MKR: ['#12B76A'],
  UNI: ['#EE46BC'],
  MATIC: ['#7F56D9'],
  COMP: ['#32D583'],
  ZRX: ['#EAECF0'],
  AVAX: ['#F04438'],
  ZEC: ['#FEB273'],
  FIL: ['#6172F3'],
  CRV: ['#FDDCAB'],
  ALGO: ['#667085'],
  SUSHI: ['#DD2590'],
  ADA: ['#175CD3'],
  DOT: ['#F670C7'],
  '1INCH': ['#AFB5D9'],
  CELO: ['#FEDF89'],
  YFI: ['#2E90FA'],
  LINK: ['#3538CD'],
  ATOM: ['#717BBC'],
  ENJ: ['#6938EF'],
  SNX: ['#36BFFA'],
  ETC: ['#039855'],
  XTZ: ['#53B1FD'],
  NEAR: ['#475467'],
  XLM: ['#F2F4F7'],
  ICP: ['#FAA7E0'],
  XMR: ['#FD853A'],
  TRX: ['#D92D20'],
  EOS: ['#444CE7'],
  RUNE: ['#D1FADF'],
  UMA: ['#F97066'],
  BLUR: ['#36BFFA'],
  WETH: ['#F04438'],
  JTO: ['#303044'],
  APE: ['#84CAFF'],
  MEME: ['#717BBC'],
  JUP: ['#FF5733'],
  WBTC: ['#33FF57'],
  GALA: ['#3357FF'],
  SUI: ['#FF33A8'],
  STX: ['#57FF33'],
  INJ: ['#5733FF'],
  TON: ['#FF33C1'],
  APT: ['#33C1FF'],
  OP: ['#C1FF33'],
  MNT: ['#FF3357'],
  ONDO: ['#33FFC1'],
  FTM: ['#C133FF'],
  BLAST: ['#FFC133'],
  ARB: ['#33C157'],
  GMMEME: ['#5733C1'],
  IMX: ['#FFC1A8'],
  GMCI30: ['#57FFC1'],
  SEI: ['#A857FF'],
  MPEPE: ['#FF5733'],
  WLD: ['#33FFC1'],
  WIF: ['#C157FF'],
  PYTH: ['#57C1FF'],
  XRP: ['#FF3357'],
  ENA: ['#5733FF'],
  TIA: ['#FF5733'],
  VRTX: ['#33FF57'],
  LDO: ['#3357FF'],
  BNB: ['#FF33A8'],
  DYDX: ['#57FF33'],
  USDT: ['#32D583'],
};

export const TOOLTIP_COLORS = {
  Background: '#303044',
};

export const INTERVAL = {
  '1MIN': ['1m', 60000, '1-minute'],
  '5MINS': ['5m', 300000, '5-minute'],
  '15MINS': ['15m', 900000, '15-minute'],
  '30MINS': ['30m', 1800000, '30-minute'],
  '1HOUR': ['1h', 360000, 'hourly'],
  '4HOURS': ['4h', 14400000, '4-hour'],
  '1DAY': ['1d', 86400000, 'daily'],
};

export const VERTEXINTERVAL = {
  '1 MIN': ['1m', CandlestickPeriod.MIN],
  '5 MINS': ['5m', CandlestickPeriod.FIVE_MIN],
  '15 MINS': ['15m', CandlestickPeriod.FIFTEEN_MIN],
  '1 HOUR': ['1h', CandlestickPeriod.HOUR],
  '4 HOURS': ['4h', CandlestickPeriod.FOUR_HOUR],
  '1 DAY': ['1d', CandlestickPeriod.DAY],
};
